stages:  
  deploy-local:
    cmd: 
    - fastapi dev api_local.py
    deps:
    - api_local.py
    - ../models/production/model.onnx
    - ../deploy_check.py
    params:
    - ../params.yaml:
      - base
      - data
      - evaluate
  # update-dvc:
  #   cmd: dvc push