stages:  
  deploy-local:
    cmd: 
    - fastapi dev api_local.py
    deps:
    - api_local.py
    - ../models/model.onnx
    - ../deploy-check.py
    params:
    - ../params.yaml:
      - base
      - data
      - evaluate