base: {data_dir: data, models_dir: models, monitor_dir: results/monitor, random_seed: 42,
  results_dir: results/evaluate}
data:
  X_test: test_data/X_test.npy
  X_train: train_data/X_train.npy
  categorical_columns: [Gender, Country, Occupation, self_employed, family_history,
    Days_Indoors, Growing_Stress, Changes_Habits, Mental_Health_History, Mood_Swings,
    Coping_Struggles, Work_Interest, Social_Weakness, care_options]
  clean_data: clean_data/clean_data.csv
  clean_data_dir: data/clean_data
  cols_to_drop: [mental_health_interview, Timestamp]
  features_used: [Gender, Country, Occupation, self_employed, family_history, Days_Indoors,
    Growing_Stress, Changes_Habits, Mental_Health_History, Mood_Swings, Coping_Struggles,
    Work_Interest, Social_Weakness, care_options]
  num_features: 14
  pred: prediction/prediction.csv
  pred_column: prediction
  preprocessor: preprocessor.pkl
  raw_data: m_health_dataset.csv
  ref_data: ref_data/ref_data.csv
  ref_data_dir: data/ref_data
  test_data_dir: data/test_data
  test_unscaled: test_data/test_unscaled.csv
  train_data_dir: data/train_data
  train_unscaled: train_data/train_unscaled.csv
  y_column: treatment
  y_test: test_data/y_test.csv
  y_train: train_data/y_train.csv
data_split: {test_size: 0.3}
evaluate: {conf_matrix: yes, expl_plot: yes, metrics: metrics.json, model_performance: model_performance.json, model_onnx: model.onnx}
monitor: {drift_report: drift_report.json, summary_report: summary_report.json}
train: {learning_rate: 0.1, max_depth: 9, model_pkl: model.pkl,
  n_estimators: 9, model_type: Gradient Boost}
environment:
  env: production
  model_baseline: 0.7
  drift_threshhold: 0.1
  prod_model_path: production
  prod_model: model_prod.onnx
  model_to_copy: model.onnx
  

